services:
  cardano-node-bp:
    image: cardano-testnet:latest
    ports:
    - 3001:3001
    volumes:
    - node-testnet:/node/testnet
    command:
    - bash
    - -c 
    - |
      initTestnet
    healthcheck:
      test: [ "CMD-SHELL", "cardano-cli query tip" ]
      interval: 5s
      start_period: 5s
      timeout: 2s
      retries: 10
    environment:
      CARDANO_NODE_SOCKET_PATH: /node/testnet/socket/node1/sock
      CARDANO_NODE_NETWORK_ID: "42"

  bootstrap-wallet:
    image: cardano-testnet:latest
    volumes:
    - node-testnet:/node/testnet
    command:
    - bash
    - -c
    - |
      transactGenesis
      sleep 3600
    environment:
      CARDANO_NODE_SOCKET_PATH: /node/testnet/socket/node1/sock
      CARDANO_NODE_NETWORK_ID: "42"
    depends_on:
      cardano-node-bp:
        condition: service_healthy

  cardano-wallet:
    image: cardanofoundation/cardano-wallet:2025.3.31
    restart: always
    ports:
    - 8090:8090
    volumes:
    - node-testnet:/node/testnet
    entrypoint: []
    command:
    - bash
    - -c
    - |
      cardano-wallet serve \
        --database /wallet/db \
        --node-socket /node/testnet/socket/node1/sock \
        --testnet /node/testnet/byron-genesis.json \
        --listen-address 0.0.0.0
    depends_on:
      cardano-node-bp:
        condition: service_healthy

volumes:
  node-testnet: {}
