from __future__ import annotations

from pathlib import Path

import yaml

from compose_gen.models import ComposeConfig

from . import services, stacks
from .metadata import VERSION


def write_compose_file(config: ComposeConfig, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write("# Code generated by Python script. DO NOT EDIT.\n")
        yaml.dump(config.model_dump(exclude_none=True), f, allow_unicode=True)


def main() -> None:
    docker_dir = Path(__file__).parent.parent.parent / "docker"

    # Define all configurations
    configs: dict[str, ComposeConfig] = {
        "mainnet-dbsync/compose": ComposeConfig(
            services={
                "db": services.db.mk_service(services.db.Options(host_port=5432)),
                "neoprism-indexer": services.neoprism.mk_service(
                    services.neoprism.Options(
                        host_port=8080,
                        dlt_source=services.neoprism.DbSyncDltSource(
                            type="dbsync",
                            args=services.neoprism.DbSyncDltSourceArgs(
                                url="<DBSYNC_URL>"
                            ),
                        ),
                    ),
                ),
            }
        ),
        "mainnet-relay/compose": ComposeConfig(
            services={
                "db": services.db.mk_service(services.db.Options(host_port=5432)),
                "neoprism-indexer": services.neoprism.mk_service(
                    services.neoprism.Options(
                        host_port=8080,
                        dlt_source=services.neoprism.RelayDltSource(
                            type="relay",
                            address="backbone.mainnet.cardanofoundation.org:3001",
                        ),
                    ),
                ),
            }
        ),
        "preprod-relay/compose": ComposeConfig(
            services={
                "db": services.db.mk_service(services.db.Options(host_port=5432)),
                "neoprism-indexer": services.neoprism.mk_service(
                    services.neoprism.Options(
                        host_port=8080,
                        network="preprod",
                        dlt_source=services.neoprism.RelayDltSource(
                            type="relay",
                            address="preprod-node.play.dev.cardano.org:3001",
                        ),
                    ),
                ),
            }
        ),
        "prism-test/compose": stacks.prism_test.mk_stack(stacks.prism_test.Options()),
        "prism-test/compose-ci": stacks.prism_test.mk_stack(
            stacks.prism_test.Options(
                neoprism_image_override=f"identus-neoprism:latest"
            )
        ),
        "blockfrost-neoprism-demo/compose": stacks.blockfrost_neoprism_demo.mk_stack(
            stacks.blockfrost_neoprism_demo.Options()
        ),
        "mainnet-universal-resolver/compose": stacks.universal_resolver.mk_stack(),
    }

    # Generate all compose files
    for name, config in configs.items():
        output_path = docker_dir / f"{name}.yml"
        write_compose_file(config, output_path)
        print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
