// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Did } from "./Did";
import type { Service } from "./Service";
import type { VerificationMethod } from "./VerificationMethod";
import type { VerificationMethodOrRef } from "./VerificationMethodOrRef";

export type DidDocument = { context: Array<string>, id: Did, verificationMethod: Array<VerificationMethod>, authentication: Array<VerificationMethodOrRef> | null, assertionMethod: Array<VerificationMethodOrRef> | null, keyAgreement: Array<VerificationMethodOrRef> | null, capabilityInvocation: Array<VerificationMethodOrRef> | null, capabilityDelegation: Array<VerificationMethodOrRef> | null, service: Array<Service> | null, };
