// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceEndpoint } from "./ServiceEndpoint";
import type { ServiceType } from "./ServiceType";

export type Service = { id: string, type: ServiceType, serviceEndpoint: ServiceEndpoint, };
