// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerificationMethod = { id: string, type: string, controller: string, publicKeyJwk: Record<string, any>, };
