services:
  cardano-node-relay:
    image: cardano-testnet:latest
    ports:
    - 3001:3001
    volumes:
    - ./testnet-local:/node/config
    command:
    - bash
    - -c 
    - |
      cardano-node run \
        --config /node/config/configuration.yaml \
        --topology /node/config/topology-relay.json \
        --database-path /node/db \
        --socket-path /node/socket \
        --host-addr 0.0.0.0 \
        --port 3001
    environment:
      CARDANO_NODE_SOCKET_PATH: /node/socket
      CARDANO_NODE_NETWORK_ID: "42"
