services:
  indexer-node:
    image: hyperledgeridentus/identus-neoprism:0.1.0
    restart: always
    ports:
      - 8080:8080
    environment:
      RUST_LOG: oura=warn,tracing::span=warn,info
      NPRISM_CARDANO_NETWORK: mainnet
      NPRISM_CARDANO_ADDR: backbone.mainnet.cardanofoundation.org:3001
      NPRISM_DB_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
