services:
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
  indexer-node:
    depends_on:
      - db
    environment:
      NPRISM_CARDANO_NETWORK: mainnet
      NPRISM_DBSYNC_URL: "<DBSYNC_URL>"
      NPRISM_DB_URL: "postgres://postgres:postgres@db:5432/postgres"
      RUST_LOG: "oura=warn,tracing::span=warn,info"
    image: hyperledgeridentus/identus-neoprism:0.1.0
    ports:
      - "8080:8080"
    restart: always
