services:
  cardano-node-bp:
    image: cardano-testnet:latest
    ports:
    - 3001:3001
    volumes:
    - node-ipc:/node/socket
    - node-genesis:/node/genesis
    - ./node-config:/node/config
    command:
    - bash
    - -c 
    - |
      initTestnet
      cardano-node run \
        --database-path /node/db \
        --socket-path /node/socket/node-bp.socket \
        --topology /node/config/topology.json \
        --config /node/genesis/node-config.json \
        --shelley-kes-key /node/genesis/delegate-keys/shelley.000.kes.skey \
        --shelley-vrf-key /node/genesis/delegate-keys/shelley.000.vrf.skey \
        --shelley-operational-certificate /node/genesis/delegate-keys/shelley.000.opcert.json \
        --host-addr 0.0.0.0 \
        --port 3001
    healthcheck:
      test: [ "CMD-SHELL", "cardano-cli query tip" ]
      interval: 5s
      start_period: 5s
      timeout: 2s
      retries: 10
    environment:
      CARDANO_NODE_SOCKET_PATH: /node/socket/node-bp.socket
      CARDANO_NODE_NETWORK_ID: "42"

  cardano-wallet:
    image: cardanofoundation/cardano-wallet:2025.3.31
    restart: always
    ports:
      - 8090:8090
    volumes:
    - node-ipc:/node/socket
    - node-genesis:/node/genesis
    entrypoint: []
    command:
    - bash
    - -c
    - |
      cardano-wallet serve \
        --database /wallet/db \
        --node-socket /node/socket/node-bp.socket \
        --testnet /node/genesis/byron-genesis.json \
        --listen-address 0.0.0.0
    depends_on:
      cardano-node-bp:
        condition: service_healthy

volumes:
  node-ipc: {}
  node-genesis: {}
