version: "3.8"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.7
    environment:
      - NETWORK=mainnet
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    ports:
      - 3001:3001
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
