[package]
name = "prism-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
log = "0.4"
prism-core = { path = "../prism-core" }
tokio = { version = "1", features = ["full"] }
