[package]
name = "prism-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21"
bytes = "1"
chrono = "0.4"
hex = "0.4"
log = "0.4"
prost = "0.11"
prost-types = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "1"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
prost-build = "0.11"

[features]
default = ["cardano"]
cardano = []
