services:
  bootstrap-testnet:
    command:
      - bash
      - "-c"
      - |
        transactGenesis
        hurl ./init-wallet.hurl
    depends_on:
      cardano-node:
        condition: service_healthy
    environment:
      CARDANO_NODE_NETWORK_ID: '42'
      CARDANO_NODE_SOCKET_PATH: /node/testnet/socket/node1/sock
      GENESIS_PAYMENT_ADDR: addr_test1qp83v2wq3z9mkcjj5ejlupgwt6tcly5mtmz36rpm8w4atvqd5jzpz23y8l4dwfd9l46fl2p86nmkkx5keewdevqxhlyslv99j3
      HURL_WALLET_BASE_URL: http://cardano-wallet:8090/v2
      HURL_WALLET_PASSPHRASE: super_secret
    image: patextreme/cardano-testnet:20250730-211809
    volumes:
      - node-testnet:/node/testnet
      - "./init-wallet.hurl:/node/init-wallet.hurl"
  cardano-dbsync:
    command:
      - "--config"
      - /config/dbsync-config.yaml
      - "--socket-path"
      - /node/testnet/socket/node1/sock
      - "--force-indexes"
    depends_on:
      cardano-node:
        condition: service_healthy
      db-dbsync:
        condition: service_healthy
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-dbsync
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: '5432'
      POSTGRES_USER: postgres
    image: ghcr.io/intersectmbo/cardano-db-sync:13.6.0.5
    restart: always
    volumes:
      - node-testnet:/node/testnet
      - "./dbsync-config.yaml:/config/dbsync-config.yaml"
  cardano-node:
    command:
      - initTestnet
    environment:
      CARDANO_NODE_NETWORK_ID: '42'
      CARDANO_NODE_SOCKET_PATH: /node/testnet/socket/node1/sock
    healthcheck:
      interval: "2s"
      retries: 30
      test:
        - CMD-SHELL
        - cardano-cli query tip
      timeout: "5s"
    image: patextreme/cardano-testnet:20250730-211809
    volumes:
      - node-testnet:/node/testnet
  cardano-wallet:
    command:
      - bash
      - "-c"
      - |
        cardano-wallet serve \
          --database /wallet/db \
          --node-socket /node/testnet/socket/node1/sock \
          --testnet /node/testnet/byron-genesis.json \
          --listen-address 0.0.0.0
    depends_on:
      cardano-node:
        condition: service_healthy
    entrypoint: []
    healthcheck:
      interval: "2s"
      retries: 30
      test:
        - CMD-SHELL
        - cardano-wallet network information
      timeout: "5s"
    image: cardanofoundation/cardano-wallet:2025.3.31
    ports:
      - "8090:8090"
    restart: always
    volumes:
      - node-testnet:/node/testnet
  db-dbsync:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      interval: "2s"
      retries: 30
      test:
        - CMD
        - pg_isready
        - "-U"
        - postgres
      timeout: "5s"
    image: postgres:16
    restart: always
  db-neoprism:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      interval: "2s"
      retries: 30
      test:
        - CMD
        - pg_isready
        - "-U"
        - postgres
      timeout: "5s"
    image: postgres:16
    restart: always
  db-prism-node:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      interval: "2s"
      retries: 30
      test:
        - CMD
        - pg_isready
        - "-U"
        - postgres
      timeout: "5s"
    image: postgres:16
    restart: always
  neoprism-standalone:
    command:
      - standalone
    depends_on:
      cardano-wallet:
        condition: service_healthy
      db-neoprism:
        condition: service_healthy
    environment:
      NPRISM_CARDANO_DBSYNC_POLL_INTERVAL: '1'
      NPRISM_CARDANO_DBSYNC_URL: "postgresql://postgres:postgres@db-dbsync:5432/postgres"
      NPRISM_CARDANO_NETWORK: mainnet
      NPRISM_CARDANO_WALLET_BASE_URL: http://cardano-wallet:8090/v2
      NPRISM_CARDANO_WALLET_PASSPHRASE: super_secret
      NPRISM_CARDANO_WALLET_PAYMENT_ADDR: addr_test1qp83v2wq3z9mkcjj5ejlupgwt6tcly5mtmz36rpm8w4atvqd5jzpz23y8l4dwfd9l46fl2p86nmkkx5keewdevqxhlyslv99j3
      NPRISM_CARDANO_WALLET_WALLET_ID: "9263a1248b046fe9e1aabc4134b03dc5c3a7ee3d"
      NPRISM_CONFIRMATION_BLOCKS: '0'
      NPRISM_DB_URL: "postgres://postgres:postgres@db-neoprism:5432/postgres"
      NPRISM_INDEX_INTERVAL: '1'
      RUST_LOG: "oura=warn,tracing::span=warn,info"
    healthcheck:
      interval: "2s"
      retries: 30
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:8080/api/_system/health
      timeout: "5s"
    image: identus-neoprism:0.3.1
    ports:
      - "8080:8080"
    restart: always
  prism-node:
    depends_on:
      bootstrap-testnet:
        condition: service_completed_successfully
      cardano-wallet:
        condition: service_healthy
      db-dbsync:
        condition: service_healthy
      db-prism-node:
        condition: service_healthy
    environment:
      NODE_CARDANO_CONFIRMATION_BLOCKS: '0'
      NODE_CARDANO_DB_SYNC_DATABASE: postgres
      NODE_CARDANO_DB_SYNC_HOST: db-dbsync:5432
      NODE_CARDANO_DB_SYNC_PASSWORD: postgres
      NODE_CARDANO_DB_SYNC_USERNAME: postgres
      NODE_CARDANO_NETWORK: testnet
      NODE_CARDANO_PAYMENT_ADDRESS: addr_test1qp83v2wq3z9mkcjj5ejlupgwt6tcly5mtmz36rpm8w4atvqd5jzpz23y8l4dwfd9l46fl2p86nmkkx5keewdevqxhlyslv99j3
      NODE_CARDANO_PRISM_GENESIS_BLOCK: '0'
      NODE_CARDANO_WALLET_API_HOST: cardano-wallet
      NODE_CARDANO_WALLET_API_PORT: '8090'
      NODE_CARDANO_WALLET_ID: "9263a1248b046fe9e1aabc4134b03dc5c3a7ee3d"
      NODE_CARDANO_WALLET_PASSPHRASE: super_secret
      NODE_LEDGER: cardano
      NODE_MOVE_SCHEDULED_TO_PENDING_PERIOD: "1s"
      NODE_PSQL_DATABASE: postgres
      NODE_PSQL_HOST: db-prism-node:5432
      NODE_PSQL_PASSWORD: postgres
      NODE_PSQL_USERNAME: postgres
      NODE_REFRESH_AND_SUBMIT_PERIOD: "1s"
    image: prism-node-fastsync:latest
    ports:
      - "50053:50053"
    restart: always
  scala-did:
    command:
      - /bin/scala-did-node
    image: pris-node-fastsync:latest
    ports:
      - "8980:8980"
    restart: always
volumes:
  node-testnet: {}
