// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Service } from "./Service";
import type { VerificationMethod } from "./VerificationMethod";

export type DidDocument = { id: string, verification_method: Array<VerificationMethod>, service: Array<Service> | null, };
