// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerificationMethod = { "Ed25519": { public_key: string, } } | { "EcdsaSecp256k1": { public_key: string, } };
