name: "Validate PR Title"

on:
  # https://github.com/amannn/action-semantic-pull-request
  # This action will not longer have access to the secrets.GITHUB_TOKEN from forked repos
  pull_request: # Do not use pull_request_target to prevent supply chain attacks
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
